import log from 'loglevel';
import { awsApiGatewayV2StageFunc } from '../../../../../src/cloudformation/parsing/resolver/resources/awsApiGatewayV2StageFunc';
import { ResolvingContext } from '../../../../../src/cloudformation/parsing/types/types';
import {
    generateAlphaNumeric,
    resolveString,
    resolveStringWithDefault,
} from '../../../../../src/cloudformation/parsing/utils/helper-utils';
import { CloudFormationResource } from '../../../../../src/cloudformation/types/cloudformation-model';

// Mock the helper functions to control their outputs.
jest.mock('../../../../../src/cloudformation/parsing/utils/helper-utils', () => ({
    generateAlphaNumeric: jest.fn(() => 'MOCKED_NUM'),
    resolveString: jest.fn((_value: unknown, _propertyName: string, _ctx: ResolvingContext) => 'resolvedApiId'),
    resolveStringWithDefault: jest.fn(
        (_prop: unknown, defaultValue: string, _propertyName: string, _ctx: ResolvingContext) => defaultValue,
    ),
}));

/**
 * Creates a fresh mock ResolvingContext for testing.
 *
 * @returns A mock ResolvingContext.
 */
function createMockContext(): ResolvingContext {
    return {
        originalTemplate: {},
        lookupMapPreProcessed: {},
        generatedIds: new Set(),
        lookupMapDynamic: {},
        currentPath: [],
        addName: jest.fn(),
        popName: jest.fn(() => ''),
        getCurrentPath: jest.fn(() => ''),
        hasParameterName: jest.fn(() => false),
        getParameter: jest.fn(),
        addParameter: jest.fn(),
        addGeneratedId: jest.fn(),
        isIdExists: jest.fn(() => false),
        getRegion: jest.fn(() => 'us-east-1'),
        getPartition: jest.fn(() => 'aws'),
        getAccountId: jest.fn(() => '123456789012'),
        getAZs: jest.fn(() => ['us-east-1a', 'us-east-1b']),
    } as unknown as ResolvingContext;
}

describe('awsApiGatewayV2StageFunc', () => {
    let mockCtx: ResolvingContext;
    let resource: CloudFormationResource;

    beforeEach(() => {
        // Create a fresh context and resource for every test.
        mockCtx = createMockContext();
        resource = {
            Properties: {
                ApiId: 'dummyApiId',
                StageName: 'dummyStageName',
            },
        } as CloudFormationResource;

        // Ensure _id and _arn are not preset.
        delete resource._id;
        delete resource._arn;

        // Reset mocks for helper functions.
        (generateAlphaNumeric as jest.Mock).mockClear();
        (resolveString as jest.Mock).mockClear();
        (resolveStringWithDefault as jest.Mock).mockClear();
    });

    describe('idGenFunc', () => {
        it('should generate a new ID if not already set', () => {
            const id = awsApiGatewayV2StageFunc.idGenFunc(
                'AWS::ApiGatewayV2::Stage',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            // The default value is built as "stage-" + generateAlphaNumeric(4, ctx)
            expect(generateAlphaNumeric).toHaveBeenCalledWith(4, mockCtx);
            expect(resolveStringWithDefault).toHaveBeenCalledWith(
                'dummyStageName',
                `stage-MOCKED_NUM`,
                'AWS::ApiGatewayV2::Stage.Properties.StageName',
                mockCtx,
            );
            expect(id).toBe(`stage-MOCKED_NUM`);
            expect(resource._id).toBe(`stage-MOCKED_NUM`);
        });

        it('should return the existing ID if already set', () => {
            resource._id = 'existingStageId';
            const id = awsApiGatewayV2StageFunc.idGenFunc(
                'AWS::ApiGatewayV2::Stage',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('existingStageId');
            expect(generateAlphaNumeric).not.toHaveBeenCalled();
            expect(resolveStringWithDefault).not.toHaveBeenCalled();
        });
    });

    describe('refFunc', () => {
        it('should return the ID generated by idGenFunc', () => {
            const id = awsApiGatewayV2StageFunc.refFunc('AWS::ApiGatewayV2::Stage', 'TestLogicalId', resource, mockCtx);
            expect(id).toBe(`stage-MOCKED_NUM`);
        });
    });

    describe('getAttFunc', () => {
        it('should return the ID when key is "Id"', () => {
            const id = awsApiGatewayV2StageFunc.getAttFunc(
                'AWS::ApiGatewayV2::Stage',
                'Id',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe(`stage-MOCKED_NUM`);
        });

        it('should warn and return the ID when an unsupported key is passed', () => {
            const warnSpy = jest.spyOn(log, 'warn').mockImplementation(() => {});
            const id = awsApiGatewayV2StageFunc.getAttFunc(
                'AWS::ApiGatewayV2::Stage',
                'UnsupportedKey',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe(`stage-MOCKED_NUM`);
            expect(warnSpy).toHaveBeenCalledWith(
                `Passed key UnsupportedKey for AWS::ApiGatewayV2::Stage, with logicalId=TestLogicalId is not supported, id will be returned`,
                resource,
                mockCtx,
            );
            warnSpy.mockRestore();
        });
    });

    describe('arnGenFunc', () => {
        it('should generate and assign a new ARN if none exists', () => {
            const arn = awsApiGatewayV2StageFunc.arnGenFunc(
                'AWS::ApiGatewayV2::Stage',
                'TestLogicalId',
                resource,
                mockCtx,
            );

            // Verify that resolveString was used to resolve the ApiId.
            expect(resolveString).toHaveBeenCalledWith(
                'dummyApiId',
                'AWS::ApiGatewayV2::Stage.Properties.ApiId',
                mockCtx,
            );

            // The ARN is built as:
            // arn:{partition}:apigateway:{region}::/apis/{resolvedApiId}/stages/{stageName}
            const expectedArn = `arn:aws:apigateway:us-east-1::/apis/resolvedApiId/stages/stage-MOCKED_NUM`;
            expect(arn).toBe(expectedArn);
            expect(resource._arn).toBe(expectedArn);
        });

        it('should return the existing ARN if it is already set', () => {
            resource._arn = 'existingArn';
            const arn = awsApiGatewayV2StageFunc.arnGenFunc(
                'AWS::ApiGatewayV2::Stage',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(arn).toBe('existingArn');
        });
    });
});
