import log from 'loglevel';
import { awsApiGatewayV2AuthorizerFunc } from '../../../../../src/cloudformation/parsing/resolver/resources/awsApiGatewayV2AuthorizerFunc';
import { ResolvingContext } from '../../../../../src/cloudformation/parsing/types/types';
import { generateAlphaNumeric, resolveString } from '../../../../../src/cloudformation/parsing/utils/helper-utils';
import { CloudFormationResource } from '../../../../../src/cloudformation/types/cloudformation-model';

// Mock helper functions to control their outputs.
jest.mock('../../../../../src/cloudformation/parsing/utils/helper-utils', () => ({
    generateAlphaNumeric: jest.fn(() => 'MOCKED_ID'),
    resolveString: jest.fn((_value: unknown, _propertyName: string, _ctx: ResolvingContext) => 'resolvedApiId'),
}));

/**
 * Creates a fresh mock ResolvingContext for testing.
 *
 * @returns A mock ResolvingContext.
 */
function createMockContext(): ResolvingContext {
    return {
        originalTemplate: {},
        lookupMapPreProcessed: {},
        generatedIds: new Set(),
        lookupMapDynamic: {},
        currentPath: [],
        addName: jest.fn(),
        popName: jest.fn(() => ''),
        getCurrentPath: jest.fn(() => ''),
        hasParameterName: jest.fn(() => false),
        getParameter: jest.fn(),
        addParameter: jest.fn(),
        addGeneratedId: jest.fn(),
        isIdExists: jest.fn(() => false),
        getRegion: jest.fn(() => 'us-east-1'),
        getPartition: jest.fn(() => 'aws'),
        getAccountId: jest.fn(() => '123456789012'),
        getAZs: jest.fn(() => ['us-east-1a', 'us-east-1b']),
    } as unknown as ResolvingContext;
}

describe('awsApiGatewayV2AuthorizerFunc', () => {
    let mockCtx: ResolvingContext;
    let resource: CloudFormationResource;

    beforeEach(() => {
        // Create fresh mock context and resource for every test.
        mockCtx = createMockContext();
        resource = {
            Properties: {
                ApiId: 'dummyApiId',
            },
        } as CloudFormationResource;

        // Ensure _id and _arn are not preset.
        delete resource._id;
        delete resource._arn;

        // Reset mocks.
        (generateAlphaNumeric as jest.Mock).mockClear();
        (resolveString as jest.Mock).mockClear();
    });

    describe('idGenFunc', () => {
        /**
         * Should generate a new ID if one is not already set.
         */
        it('should generate a new ID if not already set', () => {
            const id = awsApiGatewayV2AuthorizerFunc.idGenFunc(
                'AWS::ApiGatewayV2::Authorizer',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('MOCKED_ID');
            expect(resource._id).toBe('MOCKED_ID');
            expect(generateAlphaNumeric).toHaveBeenCalledWith(9, mockCtx);
        });

        /**
         * Should return the existing ID if it is already set.
         */
        it('should return the existing ID if already set', () => {
            resource._id = 'existingId';
            const id = awsApiGatewayV2AuthorizerFunc.idGenFunc(
                'AWS::ApiGatewayV2::Authorizer',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('existingId');
            // When an ID already exists, helper is not called.
            expect(generateAlphaNumeric).not.toHaveBeenCalled();
        });
    });

    describe('refFunc', () => {
        /**
         * Should return the ID generated by idGenFunc.
         */
        it('should return the ID generated by idGenFunc', () => {
            const id = awsApiGatewayV2AuthorizerFunc.refFunc(
                'AWS::ApiGatewayV2::Authorizer',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('MOCKED_ID');
        });
    });

    describe('getAttFunc', () => {
        /**
         * Should return the ID when the key is "AuthorizerId".
         */
        it('should return the ID when key is "AuthorizerId"', () => {
            const id = awsApiGatewayV2AuthorizerFunc.getAttFunc(
                'AWS::ApiGatewayV2::Authorizer',
                'AuthorizerId',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('MOCKED_ID');
        });

        /**
         * Should warn and return the ID when an unsupported key is passed.
         */
        it('should warn and return the ID when an unsupported key is passed', () => {
            const warnSpy = jest.spyOn(log, 'warn').mockImplementation(() => {});
            const id = awsApiGatewayV2AuthorizerFunc.getAttFunc(
                'AWS::ApiGatewayV2::Authorizer',
                'UnsupportedKey',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('MOCKED_ID');
            expect(warnSpy).toHaveBeenCalledWith(
                `Passed key UnsupportedKey for AWS::ApiGatewayV2::Authorizer, with logicalId=TestLogicalId is not supported, id will be returned`,
                resource,
                mockCtx,
            );
            warnSpy.mockRestore();
        });
    });

    describe('arnGenFunc', () => {
        /**
         * Should generate and assign a new ARN if none exists.
         */
        it('should generate and assign a new ARN if none exists', () => {
            const arn = awsApiGatewayV2AuthorizerFunc.arnGenFunc(
                'AWS::ApiGatewayV2::Authorizer',
                'TestLogicalId',
                resource,
                mockCtx,
            );

            // Verify that resolveString was used to resolve the ApiId.
            expect(resolveString).toHaveBeenCalledWith(
                'dummyApiId',
                'AWS::ApiGatewayV2::Authorizer.Properties.ApiId',
                mockCtx,
            );

            // Expected ARN format: arn:{partition}:apigateway:{region}::/apis/{resolvedApiId}/authorizers/{id}
            const expectedArn = 'arn:aws:apigateway:us-east-1::/apis/resolvedApiId/authorizers/MOCKED_ID';
            expect(arn).toBe(expectedArn);
            expect(resource._arn).toBe(expectedArn);
        });

        /**
         * Should return the existing ARN if it is already set.
         */
        it('should return the existing ARN if it is already set', () => {
            resource._arn = 'existingArn';
            const arn = awsApiGatewayV2AuthorizerFunc.arnGenFunc(
                'AWS::ApiGatewayV2::Authorizer',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(arn).toBe('existingArn');
        });
    });
});
