import log from 'loglevel';
import { awsApiGatewayDeploymentFunc } from '../../../../../src/cloudformation/parsing/resolver/resources/awsApiGatewayDeploymentFunc'; // Adjust path as needed
import { ResolvingContext } from '../../../../../src/cloudformation/parsing/types/types';
import { generateAlphaNumeric, resolveString } from '../../../../../src/cloudformation/parsing/utils/helper-utils';
import { CloudFormationResource } from '../../../../../src/cloudformation/types/cloudformation-model';

jest.mock('../../../../../src/cloudformation/parsing/utils/helper-utils', () => ({
    generateAlphaNumeric: jest.fn(() => 'MOCKED_ID'),
    resolveString: jest.fn((_value, _propertyName, _ctx) => 'resolvedRestApiId'),
}));

function createMockContext(): ResolvingContext {
    return {
        originalTemplate: {},
        lookupMapPreProcessed: {},
        generatedIds: new Set(),
        lookupMapDynamic: {},
        currentPath: [],
        addName: jest.fn(),
        popName: jest.fn(() => ''),
        getCurrentPath: jest.fn(() => ''),
        hasParameterName: jest.fn(() => false),
        getParameter: jest.fn(),
        addParameter: jest.fn(),
        addGeneratedId: jest.fn(),
        isIdExists: jest.fn(() => false),
        getRegion: jest.fn(() => 'us-east-1'),
        getPartition: jest.fn(() => 'aws'),
        getAccountId: jest.fn(() => '123456789012'),
        getAZs: jest.fn(() => ['us-east-1a', 'us-east-1b']),
    } as unknown as ResolvingContext;
}

describe('awsApiGatewayDeploymentFunc', () => {
    let mockCtx: ResolvingContext;
    let resource: CloudFormationResource;

    beforeEach(() => {
        mockCtx = createMockContext();
        resource = { Properties: { RestApiId: 'dummyRestApiId' } } as CloudFormationResource;
        delete resource._id;
        delete resource._arn;
        (generateAlphaNumeric as jest.Mock).mockClear();
        (resolveString as jest.Mock).mockClear();
    });

    describe('idGenFunc', () => {
        it('should generate a new ID if not already set', () => {
            const id = awsApiGatewayDeploymentFunc.idGenFunc(
                'AWS::ApiGateway::Deployment',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('MOCKED_ID');
            expect(resource._id).toBe('MOCKED_ID');
            expect(generateAlphaNumeric).toHaveBeenCalledWith(12, mockCtx);
        });

        it('should return the existing ID if already set', () => {
            resource._id = 'existingId';
            const id = awsApiGatewayDeploymentFunc.idGenFunc(
                'AWS::ApiGateway::Deployment',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('existingId');
            expect(generateAlphaNumeric).not.toHaveBeenCalled();
        });
    });

    describe('refFunc', () => {
        it('should return the ID generated by idGenFunc', () => {
            const id = awsApiGatewayDeploymentFunc.refFunc(
                'AWS::ApiGateway::Deployment',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('MOCKED_ID');
        });
    });

    describe('getAttFunc', () => {
        it('should return the ID when key is "DeploymentId"', () => {
            const id = awsApiGatewayDeploymentFunc.getAttFunc(
                'AWS::ApiGateway::Deployment',
                'DeploymentId',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('MOCKED_ID');
        });

        it('should warn and return the ID when an unsupported key is passed', () => {
            const warnSpy = jest.spyOn(log, 'warn').mockImplementation(() => {});
            const id = awsApiGatewayDeploymentFunc.getAttFunc(
                'AWS::ApiGateway::Deployment',
                'UnsupportedKey',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(id).toBe('MOCKED_ID');
            expect(warnSpy).toHaveBeenCalledWith(
                expect.stringContaining('Passed key UnsupportedKey'),
                resource,
                mockCtx,
            );
            warnSpy.mockRestore();
        });
    });

    describe('arnGenFunc', () => {
        it('should generate and assign a new ARN if none exists', () => {
            const arn = awsApiGatewayDeploymentFunc.arnGenFunc(
                'AWS::ApiGateway::Deployment',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(resolveString).toHaveBeenCalledWith('dummyRestApiId', 'resTyped.Properties.RestApiId', mockCtx);
            expect(arn).toBe('arn:aws:apigateway:us-east-1::/restapis/resolvedRestApiId/deployments/MOCKED_ID');
            expect(resource._arn).toBe(arn);
        });

        it('should return the existing ARN if it is already set', () => {
            resource._arn = 'existingArn';
            const arn = awsApiGatewayDeploymentFunc.arnGenFunc(
                'AWS::ApiGateway::Deployment',
                'TestLogicalId',
                resource,
                mockCtx,
            );
            expect(arn).toBe('existingArn');
        });
    });
});
